//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse_livraison
    {
        public int id_Adresse_livraison { get; set; }
        public string code_postal { get; set; }
        public Nullable<bool> isenable { get; set; }
        public Nullable<int> num_rue { get; set; }
        public string pays { get; set; }
        public string rue { get; set; }
        public string ville { get; set; }
        public Nullable<int> id_Utilisateur { get; set; }
    }
}
