//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentaire
    {
        public int id_commentaire { get; set; }
        public string commentaire1 { get; set; }
        public Nullable<System.DateTime> date_commentaire { get; set; }
        public double note { get; set; }
        public Nullable<int> id_Ligne_Commande { get; set; }
    }
}
