//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_Commande
    {
        public int id_Ligne_Commande { get; set; }
        public double prix_unitaire { get; set; }
        public Nullable<int> quantite { get; set; }
        public string Repas_libelle { get; set; }
        public Nullable<int> id_Commande { get; set; }
        public Nullable<int> id_Produit { get; set; }
    }
}
