//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int id_Produit { get; set; }
        public string description { get; set; }
        public string disponibilite { get; set; }
        public string image { get; set; }
        public Nullable<bool> isenable { get; set; }
        public string libellecommercial { get; set; }
        public string libelletechnique { get; set; }
        public double prix_unitaire { get; set; }
        public Nullable<int> stock_dispo { get; set; }
        public Nullable<int> id_FamilleRepas { get; set; }
    }
}
