//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repa
    {
        public int id_Repas { get; set; }
        public Nullable<System.TimeSpan> heure_limite { get; set; }
        public string imageurl { get; set; }
        public bool isenabled { get; set; }
        public string libelle { get; set; }
    }
}
