//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Truck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int id_Utilisateur { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string email { get; set; }
        public Nullable<bool> isenable { get; set; }
        public string login { get; set; }
        public string nom { get; set; }
        public string password { get; set; }
        public string prenom { get; set; }
        public Nullable<int> id_Genre { get; set; }
        public Nullable<int> id_Societe { get; set; }
    }
}
